---
- hosts: all
  gather_facts: False
  ignore_errors: yes
  ignore_unreachable: yes
  tasks:
  - name: --- PING TEST ---
    ansible.builtin.wait_for:
      port: 22
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    timeout: 5
