---
- hosts: localhost
  ignore_errors: yes
  gather_facts: no
  # ansible-galaxy collection install -r requirements.yml
  collections:
    - community.general
    - dellemc.os6
    - dellemc.os9
    - dellemc.os10
