# ansible-galaxy role install -r roles/requirements.yml -p <project-specific cache location>/requirements_roles -vvv
---
- hosts: localhost
  ignore_errors: yes
  gather_facts: no
  roles:
    - community.general
